package project.app_2;

import project.app_2.utils.Exception;

public class Task_2 {

    public static void main(String[] args) {

        new Exception().checkException();

    }
}
